global:
  organization: "BasileSoft"
  project: "Helmo"
  environment: "dev"
  instance: "hotfix-123"
  labels: {}
  annotations: {}
  default:
    service: {}
    deployment:
      replicas: 0
    container:
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      image:
        registry: docker.io
        path:
        version:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        request:
          cpu: 100m
          memory: 128Mi
    pod:
      serviceAccountName:
      securityContext:
        runAsNonRoot:
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Always
      dnsPolicy: ClusterFirst

  options:
    readOnlyRootFilesystem: false
    enabled: true
    image: 
      version: stable
    replicas: 0
    revisionHistoryLimit: 1
    imagePullPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 50%
        maxSurge: 50%
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      request:
        cpu: 100m
        memory: 128Mi
    terminationMessagePolicy: File
    terminationMessagePath: /dev/termination-log
    volume:
      configMap:
        
    
# Dict instead of array so I can reference them from values.
skeleton:
  enabled: true
  configMap:
    karlo:
      keys:
        fuck: you
  deployment:
    skeleton:
      initContainers:
        bullshit:
          command:
            - ash
          args:
            - '-c'
            - 'env'
          securityContext:
            runAsUser: 1000
      containers:
        web:
          command:
            - bash
          args:
            - '-c'
            - 'while true; do date; sleep 300; done'
          image: 
            path: bitnami/kubectl
            version: latest

mtls:
  enabled: false
