global:
  organization: "BasileSoft"
  project: "Helmo"
  environment: "dev"
  instance: "hotfix-123"
  labels:
    some/global/label: "true"
  annotations:
    some/global/annotation: "true"
  options:
    image: 
      registry: docker.io
      path: library/busybox
      version: latest
    replicas: 0
    revisionHistoryLimit: 1
    imagePullPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 50%
        maxSurge: 50%
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      request:
        cpu: 100m
        memory: 128Mi
    workingDir: null
    terminationMessagePolicy: File
    terminationMessagePath: /dev/termination-log
    

skeleton:
  enabled: true
  component: "skel"
  deployment:
    replicas: 2

mtls:
  enabled: true
