serviceAccount:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "1"

role:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    rules:
      - verbs:
          - create
        apiGroups:
          - ''
        resources:
          - secrets

roleBinding:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    role: mtls
    subjects:
      - kind: ServiceAccount
        name: mtls

configMap:
  mtls-script:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    files:
      - scripts/mtls.sh

job:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "3"
      argocd.argoproj.io/hook: Sync
    containers:
      script:
        image:
          registry: redshit.com
        workingDir: /script
        command: bash
        args:
          - -c
          - mtls.sh
        resources:
          limits:
            cpu: 500m
    volumes:
      script:
        configMap:
          name: mtls-script
          defaultMode: 511
