serviceAccount:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "1"

role:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    rules:
      - verbs:
          - create
        apiGroups:
          - ''
        resources:
          - secrets

roleBinding:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    role: mtls
    subjects:
      - kind: ServiceAccount
        name: mtls

configMap:
  mtls-script:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    files:
      - scripts/mtls.sh

job:
  mtls:
    annotations:
      argocd.argoproj.io/sync-wave: "3"
      argocd.argoproj.io/hook: Sync
    serviceAccountName: mtls
    containers:
      script:
        image:
          path: bitnami/kubectl
          version: latest
        workingDir: /script
        command:
          - bash
        args:
          - mtls.sh
        resources:
          limits:
            cpu: 500m
        volumeMounts:
          script:
            path: /script
          tmp:
            path: /tmp
    volumes:
      script:
        configMap:
          name: mtls-script
      tmp:
        emptyDir: {}
    restartPolicy: Never
