deployment:
  skeleton:
    containers:
      web:
        replicas: 1
    restartPolicy: Always

service:
  skeleton:
    type: clusterIP
    selector:
      app: kerli
    ports:
      - name: karlo
        protocol: TCP
        port: 80
        targetPort: 8080
        
#configMap:
#  test-files:
#    files:
#      - files/test1.txt
#      - files/test2.txt
