name: Helm Chart CI

on:
  push:
  pull_request:

jobs:
  helm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Lint Helm chart
        run: |
          helm lint .

      - name: Render Helm templates
        run: |
          helm template . --debug
